"""add duration_type

Revision ID: 3277eb2d429c
Revises: 7c0f88c06e42
Create Date: 2026-03-24 12:54:27.128097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3277eb2d429c'
down_revision: Union[str, Sequence[str], None] = '7c0f88c06e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'bookings', ['parent_id'], ['id'])
    
    duration_enum = sa.Enum('HOURLY', 'FIRST_HALF', 'SECOND_HALF', 'FULL_DAY', name='durationtypeenum')
    duration_enum.create(op.get_bind())
    op.add_column('ground_pricing', sa.Column('duration_type', duration_enum, nullable=False, server_default='HOURLY'))
    
    # Manually add EVENT to pricingcategoryenum
    op.execute("ALTER TYPE pricingcategoryenum ADD VALUE IF NOT EXISTS 'EVENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ground_pricing', 'duration_type')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'parent_id')
    # ### end Alembic commands ###
